resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: falcosecurity/artifact-operator
  newName: falcosecurity/falco-operator
  newTag: main
- name: falcosecurity/falco-operator
  newName: falcosecurity/falco-operator
  newTag: latest
